Basket Class
dylancoffey99/CS4125-Wholesaler-System-Indium pull request #22
Opened 2021-11-11 09:49 UTC by nadinefrawley

2021-11-11 14:29 UTC, wasimghazal approved these changes
as I see the order file wasn't changed and I think the basket file looks good, we can always change the basket file in future if we need that.

2021-11-11 18:01 UTC, dylancoffey99 requested changes

2021-11-11 18:01 UTC, dylancoffey99 commented on system/models/shopping/order.py
> +        return [self._order_id, self._order_items, self._customer]
I think you committed this by accident? It removed the last newline at the end of the order file. You should delete it from the push.

2021-11-12 18:36 UTC, dylancoffey99 approved these changes
Looks good to me. You never fixed order.py or implemented add/remove_item, so I just pushed it myself.

2021-11-12 18:37 UTC, merged