Created basic customer controller
dylancoffey99/CS4125-Wholesaler-System-Indium pull request #25
Opened 2021-11-14 21:36 UTC by wasimghazal

2021-11-14 21:48 UTC, dylancoffey99 reviewed
This looks good so far. We should continue from this and implement the other methods.

2021-11-14 22:08 UTC, Miracle2001 approved these changes

2021-11-15 15:12 UTC, dylancoffey99 requested changes

2021-11-15 15:12 UTC, dylancoffey99 commented on system/views/customer_view.py
> +        product_quantity_entry.grid(row=1, column=3, padx=10, pady=10)
You need to revert all the row/padding changes that you made when you edited CustomerView.
It seems like you added +1 to all the rows of the widgets. product_label.grid padding should be reverted to 10 also.

2021-11-15 15:12 UTC, dylancoffey99 commented on system/controllers/customer_controller.py
> +    def __init__(self, root, user, controller):
Maybe rename "controller" to "access_controller".

2021-11-15 15:12 UTC, dylancoffey99 commented on system/controllers/access_controller.py
>  from system.controllers.abstract_controllers import AbstractAccessController
Move the CustomerController import so it's just above AbstractAccessController.

2021-11-15 15:12 UTC, dylancoffey99 commented on system/controllers/customer_controller.py
> +        self.controller = controller
Rename here as well:
self.access_controller = access_controller

2021-11-15 15:12 UTC, dylancoffey99 commented on system/controllers/customer_controller.py
> +        self.view = views.LoginView(self.root, self.controller)
Rename here as well:
self.access_controller

2021-11-17 19:45 UTC, dylancoffey99 approved these changes
This looks good to merge as a basis. Its other methods can be continued in another pull request/branch.

2021-11-17 19:45 UTC, merged