Implemented a basic admin controller class.
dylancoffey99/CS4125-Wholesaler-System-Indium pull request #28
Opened 2021-11-14 23:20 UTC by Miracle2001

2021-11-14 23:21 UTC, wasimghazal approved these changes

2021-11-15 13:21 UTC, nadinefrawley requested changes
You need to add in a log in option for admin as they may not be able to register but they should be able to login

2021-11-15 15:20 UTC, dylancoffey99 requested changes
AdminView will also need to be updated to update the title of the window to include the logged in users name. See Wasims CustomerView changes to understand.

2021-11-15 15:20 UTC, dylancoffey99 commented on system/controllers/admin_controller.py
> +    def __init__(self, root, controller):
Same changes that I suggested to Wasim, rename "controller" to "access_controller" so there is no confusion.
Also, pass in the user that is created in the access_controller.

So overall it should be:
def __ init __ (self, root, user, access_controller):

2021-11-15 15:20 UTC, dylancoffey99 commented on system/controllers/admin_controller.py
> +        self.controller = controller
Initialise those changes as so:
self.user = user
self.access_controller = access_controller

2021-11-17 18:23 UTC, dylancoffey99 approved these changes
Looks good. We will merge this branch as it's outdated and can't use the OrderDB yet.

2021-11-17 18:24 UTC, wasimghazal approved these changes

2021-11-17 18:32 UTC, merged